name: "Bug"
description: "Report bug/issue with mod"
title: "[BUG] <title>"
labels: ["bug"]
assignees: ["zimavi"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issue
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: input
  id: minecraft-version
  attributes:
    label: Minecraft version
    description: Specify minecraft version you are using
  validations:
    required: false
- type: dropdown
  id: mod-loaders
  attributes:
    label: What mod loader are you using?
    multiple: true
    options:
      - Forge
      - Fabric
- type: textarea
  attributes:
    label: Links
    description: Leave here links to logs/crash reports and screenshots. Please use [pastebin](https://pastebin.com/), [github gist](https://gist.github.com/) and [imgur](https://imgur.com/upload).
  validations:
    required: false
